# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('eats', models.CharField(choices=[('c', 'c'), ('h', 'h'), ('o', 'o')], max_length=50)),
                ('threatened', models.BinaryField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalInJungle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Animal')),
            ],
        ),
        migrations.AddField(
            model_name='jungle',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jungle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jungle',
            name='apex_predator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Animal'),
        ),
        migrations.AddField(
            model_name='animalinjungle',
            name='jungle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Jungle'),
        ),
    ]
