# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20161205_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinjungle',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animalinjungle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
