# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20161205_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='threatened',
            field=models.BooleanField(default=False),
        ),
    ]
